# Generated by Django 4.2.11 on 2026-05-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='output_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='Language to translate to', max_length=10),
        ),
        migrations.AddField(
            model_name='textfile',
            name='output_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='Language to translate to', max_length=10),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='Input Language', max_length=10),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='Input Language', max_length=10),
        ),
    ]
