# Generated by Django 4.2.11 on 2026-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_audiofile_output_language_textfile_output_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='translated_text',
            field=models.TextField(blank=True, help_text='Translated text', null=True),
        ),
    ]
